server:
  port: 8089
  error:    include-stacktrace: on-param
  
spring:  mvc:    servlet:      path: /api/bytebank/v1
  datasource:
    url: jdbc:mysql://localhost:3306/anime?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update